application: mz-booktracker
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(js|css))
  static_files: \1
  upload: (.*\.(js|css))

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: server.main.app
